[tool.poetry]
name = "zeitdieb"
version = "0.3.0"
description = ""
authors = ["Patrick Schemitz <ps@solute.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
